AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'prod-deployment-000000000005'

  MyS3Bucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'prod-deployment-000000000004'

Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
    Description: The name of the S3 buckets