AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'prod-deployment'

Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
    Description: The name of the S3 bucket