AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CloudFormation template

Resources:
  MyS3Bucket01:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-unique-bucket-name-000001
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled


Outputs:
  BucketName:
    Description: Name of the sample Amazon S3 bucket
    Value: !Ref MyS3Bucket01