name: Deploy to AWS CloudFormation

on:
  push:
    branches:
      - main  # Or any branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Specify your AWS region

    - name: Deploy CloudFormation stack
      id: deploy
      run: |
        aws cloudformation deploy \
          --template-file ./template.yaml \
          --stack-name flask-web-api \
          --capabilities CAPABILITY_NAMED_IAM
      shell: /usr/bin/bash -e {0}
      env:
        AWS_DEFAULT_REGION: us-west-2
        AWS_REGION: us-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Get Stack Events on Failure
      if: failure()
      run: |
        aws cloudformation describe-stack-events --stack-name flask-web-api
      env:
        AWS_DEFAULT_REGION: us-west-2
        AWS_REGION: us-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
